modLoader = "javafml"
loaderVersion = "[39,)"
license = "All Rights Reserved"
[[mods]]
modId = "more_cd"
version = "${file.jarVersion}"
displayName = "More Command"
authors = "fho4565"
description = '''

'''
[[dependencies.more_cd]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.more_cd]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1,1.19)"
ordering = "NONE"
side = "BOTH"
